# Generated by Django 3.1.3 on 2020-11-03 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officedata', '0004_auto_20201103_1029'),
        ('officialdata', '0004_servicegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname_nepali', models.CharField(max_length=150, verbose_name='नाम')),
                ('staffname_english', models.CharField(max_length=150, verbose_name='Name')),
                ('staff_id', models.CharField(max_length=20, verbose_name='संकेत नं.')),
                ('citizenship_no', models.CharField(max_length=25, verbose_name='नागरिकता नं.')),
                ('citizenship_dispatcheddate', models.DateTimeField(verbose_name='जारी मिति')),
                ('citizenship_dispatcheddistrict', models.CharField(max_length=50, verbose_name='जारी जिल्ला')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Sectiontype_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.sectiontype', verbose_name='शाखा')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designation_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.designation', verbose_name='पद')),
                ('officename_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officedata.office', verbose_name='कार्यालय')),
                ('officetype_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officedata.officetype', verbose_name='कार्यरत कार्यालय')),
                ('servicegroup_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.servicegroup', verbose_name='सेवा समूह')),
            ],
        ),
    ]
