# Generated by Django 3.1.3 on 2020-11-14 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officialdata', '0001_initial'),
        ('address', '0001_initial'),
        ('officedata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname_nepali', models.CharField(max_length=150, verbose_name='नाम')),
                ('staffname_english', models.CharField(max_length=150, verbose_name='Name')),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='कर्मचारी संकेत नं.')),
                ('appointment_date', models.CharField(max_length=15, verbose_name='नियुक्ति मिति जस्तै: २०७७-०५-०५')),
                ('officeentry_date', models.CharField(max_length=15, verbose_name='कार्यालय प्रवेश मिति जस्तै: २०७७-०५-०५')),
                ('dob', models.CharField(max_length=15, verbose_name='जन्म मिति')),
                ('citizenship_no', models.CharField(max_length=25, verbose_name='नागरिकता नं.')),
                ('citizenship_dispatcheddate', models.CharField(max_length=15, verbose_name='जारी मिति')),
                ('citizenship_dispatcheddistrict', models.CharField(max_length=50, verbose_name='जारी जिल्ला')),
                ('grandfather_name', models.CharField(max_length=150, verbose_name='बाजे / ससुराको नाम')),
                ('father_name', models.CharField(max_length=150, verbose_name='बाबुको नाम')),
                ('mother_name', models.CharField(max_length=150, verbose_name='आमाको नाम')),
                ('contact_no', models.CharField(max_length=10, verbose_name='सम्पर्क नं')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='इमेल')),
                ('permanentaddr_district', models.CharField(max_length=150, verbose_name='जिल्ला')),
                ('permanentaddr_locallevel', models.CharField(max_length=150, verbose_name='स्थानीय तह')),
                ('permanentaddr_wardno', models.CharField(default='2', max_length=2, verbose_name='वडा नं.')),
                ('temporaryaddr_district', models.CharField(max_length=150, verbose_name='जिल्ला')),
                ('temporaryaddr_locallevel', models.CharField(max_length=150, verbose_name='स्थानीय तह')),
                ('temporaryaddr_wardno', models.CharField(default='2', max_length=2, verbose_name='वडा नं.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff_status', models.BooleanField(default=True, null=True, verbose_name='स्थिति')),
                ('Sectiontype_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.sectiontype', verbose_name='शाखा')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('designation_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.designation', verbose_name='पद')),
                ('employeetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.employeetype', verbose_name='कर्मचारी किसिम')),
                ('officename_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officedata.office', verbose_name='कार्यालय')),
                ('officetype_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officedata.officetype', verbose_name='कार्यरत कार्यालय')),
                ('permanentaddr_localleveltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanentaddr_localleveltype', to='address.localleveltype', verbose_name='स्थानीय तह प्रकार')),
                ('permanentaddr_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanentaddr_province', to='address.province', verbose_name='प्रदेश')),
                ('servicegroup_nepali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialdata.servicegroup', verbose_name='सेवा समूह')),
                ('temporaryaddr_localleveltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporaryaddr_localleveltype', to='address.localleveltype', verbose_name='स्थानीय तह प्रकार')),
                ('temporaryaddr_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporaryaddr_province', to='address.province', verbose_name='प्रदेश')),
            ],
        ),
    ]
