# Generated by Django 3.1.3 on 2020-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='citizenship_dispatcheddate',
            field=models.DateField(verbose_name='जारी मिति'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=20, verbose_name='कर्मचारी संकेत नं.'),
        ),
    ]
