# Generated by Django 3.1.3 on 2020-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='permanentaddr_wardno',
            field=models.CharField(default='1', max_length=2, verbose_name='वडा नं.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='temporaryaddr_wardno',
            field=models.CharField(default='1', max_length=2, verbose_name='वडा नं.'),
        ),
    ]
