# Generated by Django 3.1.3 on 2020-11-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('official', '0002_auto_20201113_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='permanentaddr_localleveltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanentaddr_localleveltype', to='address.localleveltype', verbose_name='स्थानीय तह प्रकार'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='permanentaddr_wardno',
            field=models.CharField(max_length=2, verbose_name='वडा नं.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='temporaryaddr_localleveltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporaryaddr_localleveltype', to='address.localleveltype', verbose_name='स्थानीय तह प्रकार'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='temporaryaddr_wardno',
            field=models.CharField(max_length=2, verbose_name='वडा नं.'),
        ),
    ]
