# Generated by Django 2.2.12 on 2020-11-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_auto_20201114_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_status',
        ),
    ]
