# Generated by Django 3.1.3 on 2020-11-27 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('official', '0005_remove_staff_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenshipStaffFile', models.FileField(upload_to='staff/citizenship/', verbose_name='नागरिकता')),
                ('appointmentStaffFile', models.FileField(upload_to='staff/appointment/', verbose_name='नियुक्ति पत्र')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_stafffiles', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_stafffiles', to=settings.AUTH_USER_MODEL)),
                ('staffName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='official.staff')),
            ],
        ),
    ]
