# Generated by Django 3.1.3 on 2020-11-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0006_auto_20201127_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafffiles',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stafffiles',
            name='modified_date',
        ),
    ]
