# Generated by Django 3.1.3 on 2020-11-13 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Officetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officetype_nepali', models.CharField(max_length=70, verbose_name='कार्यालयको किसिम')),
                ('officetype_english', models.CharField(max_length=70, verbose_name='Office Type')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename_nepali', models.CharField(max_length=100, verbose_name='कार्यालयको नाम')),
                ('officename_english', models.CharField(max_length=100, verbose_name='Office Name')),
                ('officeaddress', models.CharField(max_length=100, verbose_name='कार्यालयको ठेगाना')),
                ('office_wardno', models.CharField(choices=[('१', '१'), ('२', '२'), ('३', '३'), ('४', '४'), ('५', '५'), ('६', '६'), ('७', '७'), ('८', '८'), ('९', '९')], default=1, max_length=1, verbose_name='वडा नं.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('officetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officedata.officetype', verbose_name='कार्यालयको प्रकार')),
            ],
        ),
    ]
