# Generated by Django 3.0.8 on 2020-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officetype',
            name='officetype_english',
            field=models.CharField(max_length=70, verbose_name='Office Type'),
        ),
    ]
