# Generated by Django 3.1.3 on 2020-11-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officedata', '0003_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='officeaddress',
            field=models.CharField(max_length=100, verbose_name='कार्यालयको ठेगाना'),
        ),
        migrations.AlterField(
            model_name='office',
            name='officename_english',
            field=models.CharField(max_length=100, verbose_name='Office Name'),
        ),
        migrations.AlterField(
            model_name='office',
            name='officename_nepali',
            field=models.CharField(max_length=100, verbose_name='कार्यालयको नाम'),
        ),
        migrations.AlterField(
            model_name='office',
            name='officetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officedata.officetype', verbose_name='कार्यालयको प्रकार'),
        ),
    ]
