# Generated by Django 3.1.3 on 2020-11-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officedata', '0004_auto_20201103_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_wardno',
            field=models.CharField(choices=[('१', '1'), ('2', '२'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=1, max_length=1, verbose_name='वडा नं.'),
        ),
        migrations.AlterField(
            model_name='office',
            name='officetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officedata.officetype', verbose_name='कार्यालयको प्रकार'),
        ),
    ]
