# Generated by Django 3.0.8 on 2020-11-02 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officialdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation_english',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_nepali',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Employeetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeetype_nepali', models.CharField(max_length=70)),
                ('employeetype_english', models.CharField(max_length=70)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
