# Generated by Django 3.1.3 on 2020-11-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
