# Generated by Django 3.0.8 on 2020-11-02 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officialdata', '0002_auto_20201102_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='modified_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='modified_date',
            field=models.DateTimeField(default=None),
        ),
    ]
