# Generated by Django 3.1.3 on 2020-11-03 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officialdata', '0003_sectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicegroup_nepali', models.CharField(max_length=70, verbose_name='सेवा समूहको नाम')),
                ('servicegroup_english', models.CharField(max_length=70, verbose_name='Service Group Name')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
