# Generated by Django 3.0.8 on 2020-11-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialdata', '0003_auto_20201102_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetype',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='employeetype',
            name='modified_date',
        ),
    ]
