# Generated by Django 3.0.8 on 2020-11-02 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officialdata', '0004_auto_20201102_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='modified_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='employeetype_english',
            field=models.CharField(max_length=70, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='employeetype_nepali',
            field=models.CharField(max_length=70, verbose_name='कर्मचारी किसिम'),
        ),
    ]
