# Generated by Django 3.0.8 on 2020-11-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialdata', '0006_auto_20201102_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetype',
            name='modified_by',
        ),
    ]
