# Generated by Django 3.1.3 on 2020-11-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
